hyperskill_project:
  id: 89
  ide_files: https://stepik.org/media/attachments/lesson/271583/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 20 Oct 2022 15:51:55 UTC
stages:
- id: 494
  step: 7817
  is_completed: true
- id: 495
  step: 7818
  is_completed: false
- id: 496
  step: 7819
  is_completed: false
- id: 497
  step: 7820
  is_completed: false
- id: 498
  step: 7821
  is_completed: false
- id: 499
  step: 7822
  is_completed: false
